### ISSUE TITLE
Activist Army Landing Copy

### ISSUE THREAD

**Issue by yvonne-liu** [ZooeyMiller/big-issue-candidate-email#81]
## Ask your candidates to support the #ActivistArmy!

Armies of Big Issue activists have been challenging candidates about their plans to dismantle poverty. The parties have been listening and we've put prevention at the heart of this campaign. Now we need to keep it there. 

The election is just around the corner. We need you to take up The Big Issue call and ask your candidates to support our campaign for a Prevention Unit. 

We've created an email tool to make this as easy as possible, just remember to keep an eye out for your candidates' replies!

With the support of your candidates, we can build up an alliance that will guarantee - whoever's in No. 10 and whoever's your MP - that poverty prevention will be their top priority.

Ready to take action? Type in your details below and then spread the word!

**Comment by yvonne-liu** [comment]
Relates to #71

**Comment by ZooeyMiller** [comment]
I'll do this right now
